apiVersion: batch/v1
kind: Job
metadata:
  namespace: app
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: hizukayudai/ruby:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "bundle exec rake db:create && bundle exec rake db:migrate"]
        envFrom:
        - configMapRef:
            name: rails-config
      restartPolicy: Never